{"uuid": "0944f803-45eb-4dde-9cba-e6a109b3e4fe", "children": ["0fea43e3-7041-4d13-b6b0-a3506530f130", "67777fd7-9941-4cbf-9474-78433e1d4234", "9b1c7359-a09d-42e1-b6ad-c8ba6faf39ca", "43fd605f-7b13-4f31-b290-40287b1e3943", "41bf6705-616b-444e-98f7-62e89a7b96b3", "1b69ba12-7b30-4e65-b19c-e526b08b82c6", "8100df0d-17c6-4eab-a805-4fce48acf572", "b4370565-ffe4-4dc7-8a97-3f0525345b29", "f5d40cad-5b39-47f2-95e3-b179bc70e225", "67a3e72d-3f35-4f22-82d1-992c326dc3cf", "23161abe-e692-4198-b29c-068035e9c646", "a8ac9736-cde8-4756-8352-63d8884886b6"], "befores": [{"name": "session_fixtrue10", "status": "broken", "statusDetails": {"message": "KeyError: 'date3'\n", "trace": "  File \"C:\\Users\\GuoBiaoBiao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\GuoBiaoBiao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\GuoBiaoBiao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\PyCharm\\PycharmProjects\\requests\\conftest.py\", line 80, in session_fixtrue10\n    date=date1[\"date3\"]\n"}, "start": 1586522703147, "stop": 1586522703147}], "start": 1586522703147, "stop": 1586522703428}